/**
 * The A4 readability numbers (GH-186, spec 2026-09-28 sec 3). Numbers only:
 * every later task imports from here and retypes nothing. Approved at gate
 * G-NUM on 29 Sep.
 *
 * `radiusTiles` is the OUTER edge of the ring core, and it is the CLASS value.
 * The radius a unit actually draws is per TYPE:
 * `max(class value, 1.15 x that type's own hull half-diagonal)`, so no hull
 * pokes out of its ring and no unit inherits another's size. The per-type table
 * is `RADIUS_BY_TYPE`, generated by `cd tools && npx tsx
 * src/perf/unit-footprints.ts` (which prints the literal) and pinned against a
 * fresh measurement by `tools/src/perf/unit-footprints.test.ts`.
 */

export type RingClass = 'foot' | 'light' | 'armour' | 'air';

/** isAir first, then wheeled && isSoft -> light, wheeled -> armour, else foot. */
export function ringClassOf(t: { isAir: boolean; wheeled: boolean; isSoft: boolean }): RingClass {
  if (t.isAir) return 'air';
  if (t.wheeled) return t.isSoft ? 'light' : 'armour';
  return 'foot';
}

/**
 * Render-side class overrides, keyed by unit type id. The sim classes
 * `dozer_d9` as foot (role `engineer` is in its FOOT_ROLES, and
 * `mobility.wheeled` is not authored), so `ringClassOf` alone would give a
 * tracked 1.26-tile hull the rifleman's ring. Sim data is not ours to change
 * (it would move the pathing domain); the ring reads it as what its flags give
 * once it is a vehicle: soft-skinned, so `light`.
 */
export const RING_CLASS_OVERRIDE: Readonly<Record<string, RingClass>> = { dozer_d9: 'light' };

export const SELECTION_RING = {
  radiusTiles: { foot: 0.45, light: 0.55, armour: 0.7, air: 0.35 },
  thicknessTiles: 0.06,
  /** Screen-pixel floor on the thickness (holds at the 0.35 zoom clamp). */
  minThicknessPx: 1.5,
  featherTiles: 0.015,
  coreAlpha: 0.9,
  /** Outside the core only. */
  haloTiles: 0.03,
  /** 0 means off (Q4). */
  haloAlpha: 0.35,
  capacity: 256,
} as const satisfies {
  radiusTiles: Readonly<Record<RingClass, number>>;
  thicknessTiles: number;
  minThicknessPx: number;
  featherTiles: number;
  coreAlpha: number;
  haloTiles: number;
  haloAlpha: number;
  capacity: number;
};

export const HP_BAR = { widthPx: 24, heightPx: 3, framePx: 1, frameAlpha: 0.8 } as const;

/**
 * Ring outer radius per unit type id, in tiles. GENERATED -- do not hand-edit;
 * regenerate with `cd tools && npx tsx src/perf/unit-footprints.ts`.
 * Types with no GLB (billboard only) and the paramotor (canopy and rigging
 * cannot be separated from its body, so it falls back) carry their class value.
 */
export const RADIUS_BY_TYPE: Readonly<Record<string, number>> = {
  mbt_lavi: 1.15, ifv_namer: 1.6, apc_eitan: 1.51, apc_kipod: 1.51, scout_shachaf: 0.97,
  inf_squad: 0.56, mortar_team: 0.58, sniper_team: 0.51, sarim_rifles: 0.49,
  at_team: 0.45, demo_squad: 0.45, yahalom_squad: 0.45, breach_team: 0.45, militia_cell: 0.45,
  rpg_team: 0.45, atgm_cell: 0.45, mortar_crew: 0.45, charge_squad: 0.45, digger_crew: 0.45,
  recoilless_team: 0.45, civilians: 0.45,
  jeep_shoded: 1.03, technical: 1.02, dozer_d9: 1.46, rocket_battery: 1.16, moto_rpg: 0.55,
  gun_truck: 0.55, manpad_team: 0.55,
  heli_peten: 0.9, paramotor: 0.35, recon_drone: 0.35, attack_drone: 0.35, loiter_drone: 0.35,
};

/** The ring radius for a unit type: its own row, else the class value. */
export function ringRadiusFor(typeId: string, cls: RingClass): number {
  return RADIUS_BY_TYPE[typeId] ?? SELECTION_RING.radiusTiles[cls];
}
