/**
 * The A4 readability numbers (GH-186, spec 2026-09-28 sec 3). Numbers only:
 * every later task imports from here and retypes nothing. Approved at gate
 * G-NUM on 29 Sep.
 *
 * `radiusTiles` is the OUTER edge of the ring core, and it is the CLASS value.
 * The radius a unit actually draws is per TYPE:
 * `max(class value, 1.15 x that type's own hull half-diagonal)`, so no hull
 * pokes out of its ring and no unit inherits another's size. The per-type table
 * is `RADIUS_BY_TYPE`, generated by `cd tools && npx tsx
 * src/perf/unit-footprints.ts` (which prints the literal) and pinned against a
 * fresh measurement by `tools/src/perf/unit-footprints.test.ts`.
 */

export type RingClass = 'foot' | 'light' | 'armour' | 'air';

/** isAir first, then wheeled && isSoft -> light, wheeled -> armour, else foot. */
export function ringClassOf(t: { isAir: boolean; wheeled: boolean; isSoft: boolean }): RingClass {
  if (t.isAir) return 'air';
  if (t.wheeled) return t.isSoft ? 'light' : 'armour';
  return 'foot';
}

/**
 * Render-side class overrides, keyed by unit type id. The sim classes
 * `dozer_d9` as foot (role `engineer` is in its FOOT_ROLES, and
 * `mobility.wheeled` is not authored), so `ringClassOf` alone would give a
 * tracked 1.26-tile hull the rifleman's ring. Sim data is not ours to change
 * (it would move the pathing domain); the ring reads it as what its flags give
 * once it is a vehicle: soft-skinned, so `light`.
 */
export const RING_CLASS_OVERRIDE: Readonly<Record<string, RingClass>> = { dozer_d9: 'light' };

/**
 * GH-346 (the lead, 2 Oct: "bigrings" ships) made the selected ring bigger
 * and bolder: `thicknessTiles` 0.06 -> 0.10, `minThicknessPx` 1.5 -> 2.5,
 * `coreAlpha` 0.9 -> 0.95, `haloAlpha` 0.35 -> 0.5, and the drawn radius x
 * `SELECTED_RING_SCALE`. `radiusTiles` and the generated tables below are
 * still the TYPE's own footprint ring -- the team ring draws at exactly that.
 * Measurements: docs/superpowers/specs/2026-10-02-readability-design.md.
 */
export const SELECTION_RING = {
  radiusTiles: { foot: 0.45, light: 0.55, armour: 0.7, air: 0.35 },
  thicknessTiles: 0.1,
  /** Screen-pixel floor on the thickness (holds at the 0.35 zoom clamp). */
  minThicknessPx: 2.5,
  featherTiles: 0.015,
  coreAlpha: 0.95,
  /** Outside the core only. */
  haloTiles: 0.03,
  /** 0 means off (Q4). */
  haloAlpha: 0.5,
  capacity: 256,
} as const satisfies {
  radiusTiles: Readonly<Record<RingClass, number>>;
  thicknessTiles: number;
  minThicknessPx: number;
  featherTiles: number;
  coreAlpha: number;
  haloTiles: number;
  haloAlpha: number;
  capacity: number;
};

/** The selected ring's radius and ellipse axes are the type's own x this
 *  (GH-346): a foot ring 40.7 -> 50.9 px wide at zoom 1. */
export const SELECTED_RING_SCALE = 1.25;

/**
 * GH-346: the faint TEAM ring under every unselected unit on open ground --
 * the same radius or ellipse its selection ring has at 1x, in team colour,
 * quieter than a selection. Its own `SelectionRingBatch` (+1 draw call while
 * any unit is in view). Capacity covers the GDD's 300 units with margin; a
 * unit past it simply draws no team ring.
 */
export const TEAM_RING = {
  thicknessTiles: 0.05,
  minThicknessPx: 1.5,
  coreAlpha: 0.55,
  haloAlpha: 0.3,
  capacity: 512,
} as const;

/** `frameAlpha` 1.0, not the 0.8 G-NUM approved: at 0.8 the frame read only
 *  as a slightly darker edge on the mock, at 1.0 as a clear outline (G-MOCK,
 *  the lead, 29 Sep: "Frame 1.0"). */
export const HP_BAR = { widthPx: 24, heightPx: 3, framePx: 1, frameAlpha: 1 } as const;

/**
 * Ring outer radius per unit type id, in tiles. GENERATED -- do not hand-edit;
 * regenerate with `cd tools && npx tsx src/perf/unit-footprints.ts`.
 * Types with no GLB (billboard only) and the paramotor (canopy and rigging
 * cannot be separated from its body, so it falls back) carry their class value.
 */
export const RADIUS_BY_TYPE: Readonly<Record<string, number>> = {
  // dozer_d9 and scout_shachaf re-measured from their A3.2 Meshy exports (GH-185, 2026-09-30).
  mbt_lavi: 1.15, ifv_namer: 1.61, apc_eitan: 1.49, apc_kipod: 1.56, scout_shachaf: 1.01,
  // B7 (GH-179, 2026-10-01): re-measured from the Meshy figures that replaced the
  // supplied bipeds -- three men in kit's line read narrower than the supplied
  // rifleman, the prone sniper pair wider than the sculpt.
  // 2026-10-05: inf_squad 0.47 -> 0.49 and sarim_rifles 0.57 -> 0.60, re-measured
  // when their `idle` became the retargeted capture (tools/units/mocap.py): the
  // soldier's low ready and the Sarim's bladed stance stand wider than rig.py's.
  inf_squad: 0.49, mortar_team: 0.55, sniper_team: 0.62, sarim_rifles: 0.6,
  // `at_team` 0.5 since the Meshy Spike landed (A3.1 stage 2, 2026-10-05): a 1.2 m
  // canister reaching further forward of the kneeling gunner than the 1.16 m kit tube.
  at_team: 0.5, demo_squad: 0.45, yahalom_squad: 0.54, breach_team: 0.45, militia_cell: 0.45,
  // `atgm_cell` reads 0.49 since its Meshy mesh landed (B3, 2026-09-30): the same
  // rear-shin-back kneel as `recoilless_team` below, two figures wide.
  // ...and 0.5 since the Meshy ATGM post (A3.1 stage 2, 2026-10-05), its four legs wider than kit's three.
  rpg_team: 0.45, atgm_cell: 0.5, mortar_crew: 0.45, charge_squad: 0.45, digger_crew: 0.45,
  // `recoilless_team` read 0.48 when its Meshy mesh landed (B2, 2026-09-30): a real
  // kneel with the rear shin laid back is a wider footprint than the kit pair. 0.46
  // since its tube moved from the hip onto the shoulder (2026-10-01), shorter in front.
  recoilless_team: 0.46, civilians: 0.45,
  jeep_shoded: 1.03, technical: 1.02, dozer_d9: 1.56, rocket_battery: 1.16, moto_rpg: 0.55,
  // `gun_truck` measured 1.17 once its mesh landed (B2, 2026-09-30; 1.15 x its own
  // 5.4 m footprint) -- it was the infantry class 0.55 while billboard-only.
  gun_truck: 1.17, manpad_team: 0.55,
  heli_peten: 0.9, paramotor: 0.35, recon_drone: 0.36, attack_drone: 0.35,
  // `loiter_drone` reads 0.58 since its mesh landed (B2, 2026-09-30): 1.15 x its own
  // 2.43 m shipped span; it was the 0.35 air class while billboard-only.
  loiter_drone: 0.58,
  // E5 (GH-181, 2026-10-01): the bought-only Shmamit team and Peten Gunship, from a fresh
  // `tools/src/perf/unit-footprints.ts` run (footprint 0.476 and 0.778 tile).
  recon_zikit: 0.55, heli_peten_gunship: 0.9,
};

/** The ring radius for a unit type: its own row, else the class value. */
export function ringRadiusFor(typeId: string, cls: RingClass): number {
  return RADIUS_BY_TYPE[typeId] ?? SELECTION_RING.radiusTiles[cls];
}

/**
 * G-MOCK (the lead, 29 Sep: "Team colour + ellipse"): a GROUND VEHICLE's ring
 * is a hull-aligned ellipse, not a circle -- a circle big enough to clear a
 * 2.4:1 hull is mostly empty ground either side of it. Its semi-axes are the
 * hull's own half-extent plus `ELLIPSE_PAD_TILES`, along the hull (mesh +X,
 * forward under the mesh contract) and across it, and it turns with the
 * hull's heading. Infantry, other foot units and air keep their circle.
 */
export const ELLIPSE_PAD_TILES = 0.3;

export interface RingEllipse {
  /** Semi-axis along the hull's heading, tiles. */
  readonly along: number;
  /** Semi-axis across it, tiles. */
  readonly across: number;
  /** Where the hull's centre sits along the heading from the unit's origin,
   *  tiles (negative = behind). The ring is centred there (fix round 1). */
  readonly offsetAlong: number;
}

/**
 * Ellipse per ground-vehicle type id, in tiles, for every type with a vehicle
 * GLB whose ring class is `light` or `armour`: semi-axes starting at the
 * mocked `hull half-extent + ELLIPSE_PAD_TILES` and scaled up, at the same
 * aspect, until all four hull corners are inside (fix round 1 -- the Namer,
 * Eitan, D9 and Kipod grew; the other five already held their corners), and
 * the hull box's centre along the heading (`offsetAlong`). GENERATED -- do not hand-edit;
 * regenerate with `cd tools && npx tsx src/perf/unit-footprints.ts`, and
 * `tools/src/perf/unit-footprints.test.ts` pins it against a fresh
 * measurement. A type absent here draws the circle `ringRadiusFor` gives.
 */
export const ELLIPSE_BY_TYPE: Readonly<Record<string, RingEllipse>> = {
  mbt_lavi: { along: 1.17, across: 0.78, offsetAlong: -0.18 },
  ifv_namer: { along: 1.61, across: 1.05, offsetAlong: 0 },
  apc_eitan: { along: 1.52, across: 0.83, offsetAlong: 0 },
  jeep_shoded: { along: 1.1, across: 0.69, offsetAlong: 0 },
  // Both re-measured 2026-09-30 (GH-185) from the Meshy exports by
  // `tools/src/perf/unit-footprints.ts`.
  dozer_d9: { along: 1.53, across: 1.1, offsetAlong: 0 },
  scout_shachaf: { along: 1.07, across: 0.72, offsetAlong: 0 },
  apc_kipod: { along: 1.57, across: 0.97, offsetAlong: 0 },
  technical: { along: 1.13, across: 0.6, offsetAlong: 0.01 },
  // B2 (2026-09-30): the Meshy gun truck, 5.4 m x 2.8 m, from a fresh `ellipseFor`.
  gun_truck: { along: 1.2, across: 0.77, offsetAlong: 0 },
  rocket_battery: { along: 1.25, across: 0.64, offsetAlong: 0.01 },
};

/**
 * Selection-ring GRID numbers (Task 5, measured; moved here in fix round 1 so
 * every ring number lives in one module). A ring whose larger semi-axis is
 * over `RING_LARGE_TILES` is conformed on a `RING_GRID_LARGE` x
 * `RING_GRID_LARGE` grid instead of 4 x 4: on 4 x 4 a Namer's ellipse was
 * under the ground at 3.9% of vehicle placements on tel_marum (worst 0.114
 * wu) and 5.0% on qarn_hadid (0.136); on 6 x 6, 0.2% / 0.1% (0.015 / 0.017)
 * -- and 0.3% / 0.1% (0.027 / 0.026) once fix round 1 grew it to 1.61 x 1.03
 * to hold its hull corners; a 7 x 7 grid would bury none.
 * No foot ring (<= 0.58) was ever buried on 4 x 4; the Peten's 0.9 circle
 * was (0.4%). `RING_SAG_STEPS` is the lift's sag lattice: 2 buried exactly the
 * placements 4 did, by exactly as much, at under half the height samples.
 * `units/selection-ring.ts` has the account; `tools/src/ring_burial.test.ts`
 * pins it on the map.
 */
export const RING_GRID_LARGE = 6;
export const RING_LARGE_TILES = 0.72;
/**
 * Fix round 2: a third tier. The four ellipses fix round 1 grew to hold their
 * hull corners (Namer 1.61, Kipod 1.54, Eitan 1.53, D9 1.47 along) sag more
 * on 6 x 6 -- the Namer to 0.027 wu at 0.3% of tel_marum's vehicle
 * placements -- so a ring whose larger semi-axis is over `RING_XL_TILES` is
 * conformed on 7 x 7, which buries none of them on either relief map. The
 * Lavi (1.17) and the Grad (1.25) stay on 6 x 6, where they bury nothing.
 */
export const RING_GRID_XL = 7;
/** 1.28 until GH-346, which thickened the selected ring's band (0.066 ->
 *  0.11 tile at zoom 1). The sweep measures burial across the whole band, so
 *  a thicker band reaches further inside the grid: on 6 x 6 a 1.27-tile
 *  circle then buried 0.0214 wu and 1.25 0.0203 on tel_marum. Lowered until
 *  the boundary sweep passes: 1.23 on 6 x 6 reads 0.0183 / 0.0053, and 1.22
 *  on 7 x 7 buries nothing. */
export const RING_XL_TILES = 1.23;
/*
 * The two thresholds were 0.75 and 1.4 until fix round 3, which swept rings
 * AT each boundary and one 0.01 step either side, at eight headings and
 * quarter-tile offsets, over every steep tile of both relief maps
 * (`tools/src/ring_burial.test.ts`, "the tier boundaries"): a 0.75 ring on
 * 4 x 4 buried 0.024 wu on tel_marum and a 1.4 ring on 6 x 6 0.038 -- past the
 * 0.02 limit, so a future type landing just under either boundary could
 * bury. Lowered until the sweep passes (1.28 has since become 1.23, above): 0.72 on 4 x 4 reads 0.0194 and 1.28 on
 * 6 x 6 0.0185 (9-offset whole-map sweep). No shipped type changed grid: the
 * largest foot ring is 0.58, the Peten 0.9, the Grad 1.25, and the four XL
 * ellipses start at 1.47.
 */
export const RING_SAG_STEPS = 2;

/**
 * GH-346: a fourth tier, for the SELECTED ring at `SELECTED_RING_SCALE`.
 * x1.25 takes the Namer's ellipse to 2.01 x 1.31 tiles, and on 7 x 7 the
 * sweep (`tools/src/ring_burial_selected.test.ts`) buried it 0.032 wu on
 * tel_marum, the D9 0.023 and the Kipod 0.023 -- past the 0.02 limit. Probed
 * worst case, a CIRCLE at every heading over both relief maps' steep tiles:
 * on 7 x 7 a 1.5-tile circle buries 0.0098 / 0.0100 and 1.6 buries 0.019 /
 * 0.030; on 9 x 9 nothing up to 1.8 buries at all and 2.0 buries 0.018 /
 * 0.029. So a ring over 1.5 tiles is conformed on 9 x 9. No shipped CIRCLE
 * reaches 1.5 even selected (the Peten's 0.9 x 1.25 = 1.125); a future type
 * whose selected circle passed ~1.9 would bury on 9 x 9 and the selected
 * sweep would say so.
 */
export const RING_GRID_XXL = 9;
export const RING_XXL_TILES = 1.5;

/**
 * The ring's per-slot position cache (fix round 1, the lead's "Cache +
 * accept", 29 Sep): a ring's grid is rebuilt only when its unit has moved
 * more than `moveTiles` or turned more than `turnRad` since the last build,
 * or its size, shape or grid changed. Otherwise the vertices from that build
 * are drawn again -- a ring may therefore sit up to 0.05 tile behind a unit
 * creeping forward, or 2 degrees behind a turning hull, before it catches up.
 */
export const RING_CACHE = { moveTiles: 0.05, turnRad: (2 * Math.PI) / 180 } as const;
