/**
 * The A4 readability numbers (GH-186, spec 2026-09-28 sec 3). Numbers only:
 * every later task imports from here and retypes nothing. Approved at gate
 * G-NUM on 29 Sep.
 *
 * `radiusTiles` is the OUTER edge of the ring core, and it is the CLASS value.
 * The radius a unit actually draws is per TYPE:
 * `max(class value, 1.15 x that type's own hull half-diagonal)`, so no hull
 * pokes out of its ring and no unit inherits another's size. The per-type table
 * is `RADIUS_BY_TYPE`, generated by `cd tools && npx tsx
 * src/perf/unit-footprints.ts` (which prints the literal) and pinned against a
 * fresh measurement by `tools/src/perf/unit-footprints.test.ts`.
 */

export type RingClass = 'foot' | 'light' | 'armour' | 'air';

/** isAir first, then wheeled && isSoft -> light, wheeled -> armour, else foot. */
export function ringClassOf(t: { isAir: boolean; wheeled: boolean; isSoft: boolean }): RingClass {
  if (t.isAir) return 'air';
  if (t.wheeled) return t.isSoft ? 'light' : 'armour';
  return 'foot';
}

/**
 * Render-side class overrides, keyed by unit type id. The sim classes
 * `dozer_d9` as foot (role `engineer` is in its FOOT_ROLES, and
 * `mobility.wheeled` is not authored), so `ringClassOf` alone would give a
 * tracked 1.26-tile hull the rifleman's ring. Sim data is not ours to change
 * (it would move the pathing domain); the ring reads it as what its flags give
 * once it is a vehicle: soft-skinned, so `light`.
 */
export const RING_CLASS_OVERRIDE: Readonly<Record<string, RingClass>> = { dozer_d9: 'light' };

export const SELECTION_RING = {
  radiusTiles: { foot: 0.45, light: 0.55, armour: 0.7, air: 0.35 },
  thicknessTiles: 0.06,
  /** Screen-pixel floor on the thickness (holds at the 0.35 zoom clamp). */
  minThicknessPx: 1.5,
  featherTiles: 0.015,
  coreAlpha: 0.9,
  /** Outside the core only. */
  haloTiles: 0.03,
  /** 0 means off (Q4). */
  haloAlpha: 0.35,
  capacity: 256,
} as const satisfies {
  radiusTiles: Readonly<Record<RingClass, number>>;
  thicknessTiles: number;
  minThicknessPx: number;
  featherTiles: number;
  coreAlpha: number;
  haloTiles: number;
  haloAlpha: number;
  capacity: number;
};

/** `frameAlpha` 1.0, not the 0.8 G-NUM approved: at 0.8 the frame read only
 *  as a slightly darker edge on the mock, at 1.0 as a clear outline (G-MOCK,
 *  the lead, 29 Sep: "Frame 1.0"). */
export const HP_BAR = { widthPx: 24, heightPx: 3, framePx: 1, frameAlpha: 1 } as const;

/**
 * Ring outer radius per unit type id, in tiles. GENERATED -- do not hand-edit;
 * regenerate with `cd tools && npx tsx src/perf/unit-footprints.ts`.
 * Types with no GLB (billboard only) and the paramotor (canopy and rigging
 * cannot be separated from its body, so it falls back) carry their class value.
 */
export const RADIUS_BY_TYPE: Readonly<Record<string, number>> = {
  mbt_lavi: 1.15, ifv_namer: 1.6, apc_eitan: 1.49, apc_kipod: 1.56, scout_shachaf: 0.97,
  inf_squad: 0.56, mortar_team: 0.58, sniper_team: 0.51, sarim_rifles: 0.49,
  at_team: 0.45, demo_squad: 0.45, yahalom_squad: 0.45, breach_team: 0.45, militia_cell: 0.45,
  rpg_team: 0.45, atgm_cell: 0.45, mortar_crew: 0.45, charge_squad: 0.45, digger_crew: 0.45,
  recoilless_team: 0.45, civilians: 0.45,
  jeep_shoded: 1.03, technical: 1.02, dozer_d9: 1.46, rocket_battery: 1.16, moto_rpg: 0.55,
  gun_truck: 0.55, manpad_team: 0.55,
  heli_peten: 0.9, paramotor: 0.35, recon_drone: 0.36, attack_drone: 0.35, loiter_drone: 0.35,
};

/** The ring radius for a unit type: its own row, else the class value. */
export function ringRadiusFor(typeId: string, cls: RingClass): number {
  return RADIUS_BY_TYPE[typeId] ?? SELECTION_RING.radiusTiles[cls];
}

/**
 * G-MOCK (the lead, 29 Sep: "Team colour + ellipse"): a GROUND VEHICLE's ring
 * is a hull-aligned ellipse, not a circle -- a circle big enough to clear a
 * 2.4:1 hull is mostly empty ground either side of it. Its semi-axes are the
 * hull's own half-extent plus `ELLIPSE_PAD_TILES`, along the hull (mesh +X,
 * forward under the mesh contract) and across it, and it turns with the
 * hull's heading. Infantry, other foot units and air keep their circle.
 */
export const ELLIPSE_PAD_TILES = 0.3;

export interface RingEllipse {
  /** Semi-axis along the hull's heading, tiles. */
  readonly along: number;
  /** Semi-axis across it, tiles. */
  readonly across: number;
  /** Where the hull's centre sits along the heading from the unit's origin,
   *  tiles (negative = behind). The ring is centred there (fix round 1). */
  readonly offsetAlong: number;
}

/**
 * Ellipse per ground-vehicle type id, in tiles, for every type with a vehicle
 * GLB whose ring class is `light` or `armour`: semi-axes starting at the
 * mocked `hull half-extent + ELLIPSE_PAD_TILES` and scaled up, at the same
 * aspect, until all four hull corners are inside (fix round 1 -- the Namer,
 * Eitan, D9 and Kipod grew; the other five already held their corners), and
 * the hull box's centre along the heading (`offsetAlong`). GENERATED -- do not hand-edit;
 * regenerate with `cd tools && npx tsx src/perf/unit-footprints.ts`, and
 * `tools/src/perf/unit-footprints.test.ts` pins it against a fresh
 * measurement. A type absent here draws the circle `ringRadiusFor` gives.
 */
export const ELLIPSE_BY_TYPE: Readonly<Record<string, RingEllipse>> = {
  mbt_lavi: { along: 1.17, across: 0.78, offsetAlong: -0.18 },
  ifv_namer: { along: 1.61, across: 1.03, offsetAlong: 0 },
  apc_eitan: { along: 1.52, across: 0.83, offsetAlong: 0 },
  jeep_shoded: { along: 1.1, across: 0.69, offsetAlong: 0 },
  dozer_d9: { along: 1.47, across: 0.87, offsetAlong: 0 },
  scout_shachaf: { along: 1.07, across: 0.65, offsetAlong: 0 },
  apc_kipod: { along: 1.57, across: 0.97, offsetAlong: 0 },
  technical: { along: 1.13, across: 0.6, offsetAlong: 0.01 },
  rocket_battery: { along: 1.25, across: 0.64, offsetAlong: 0.01 },
};

/**
 * Selection-ring GRID numbers (Task 5, measured; moved here in fix round 1 so
 * every ring number lives in one module). A ring whose larger semi-axis is
 * over `RING_LARGE_TILES` is conformed on a `RING_GRID_LARGE` x
 * `RING_GRID_LARGE` grid instead of 4 x 4: on 4 x 4 a Namer's ellipse was
 * under the ground at 3.9% of vehicle placements on tel_marum (worst 0.114
 * wu) and 5.0% on qarn_hadid (0.136); on 6 x 6, 0.2% / 0.1% (0.015 / 0.017)
 * -- and 0.3% / 0.1% (0.027 / 0.026) once fix round 1 grew it to 1.61 x 1.03
 * to hold its hull corners; a 7 x 7 grid would bury none.
 * No foot ring (<= 0.58) was ever buried on 4 x 4; the Peten's 0.9 circle
 * was (0.4%). `RING_SAG_STEPS` is the lift's sag lattice: 2 buried exactly the
 * placements 4 did, by exactly as much, at under half the height samples.
 * `units/selection-ring.ts` has the account; `tools/src/ring_burial.test.ts`
 * pins it on the map.
 */
export const RING_GRID_LARGE = 6;
export const RING_LARGE_TILES = 0.72;
/**
 * Fix round 2: a third tier. The four ellipses fix round 1 grew to hold their
 * hull corners (Namer 1.61, Kipod 1.54, Eitan 1.53, D9 1.47 along) sag more
 * on 6 x 6 -- the Namer to 0.027 wu at 0.3% of tel_marum's vehicle
 * placements -- so a ring whose larger semi-axis is over `RING_XL_TILES` is
 * conformed on 7 x 7, which buries none of them on either relief map. The
 * Lavi (1.17) and the Grad (1.25) stay on 6 x 6, where they bury nothing.
 */
export const RING_GRID_XL = 7;
export const RING_XL_TILES = 1.28;
/*
 * The two thresholds were 0.75 and 1.4 until fix round 3, which swept rings
 * AT each boundary and one 0.01 step either side, at eight headings and
 * quarter-tile offsets, over every steep tile of both relief maps
 * (`tools/src/ring_burial.test.ts`, "the tier boundaries"): a 0.75 ring on
 * 4 x 4 buried 0.024 wu on tel_marum and a 1.4 ring on 6 x 6 0.038 -- past the
 * 0.02 limit, so a future type landing just under either boundary could
 * bury. Lowered until the sweep passes: 0.72 on 4 x 4 reads 0.0194 and 1.28 on
 * 6 x 6 0.0185 (9-offset whole-map sweep). No shipped type changed grid: the
 * largest foot ring is 0.58, the Peten 0.9, the Grad 1.25, and the four XL
 * ellipses start at 1.47.
 */
export const RING_SAG_STEPS = 2;

/**
 * The ring's per-slot position cache (fix round 1, the lead's "Cache +
 * accept", 29 Sep): a ring's grid is rebuilt only when its unit has moved
 * more than `moveTiles` or turned more than `turnRad` since the last build,
 * or its size, shape or grid changed. Otherwise the vertices from that build
 * are drawn again -- a ring may therefore sit up to 0.05 tile behind a unit
 * creeping forward, or 2 degrees behind a turning hull, before it catches up.
 */
export const RING_CACHE = { moveTiles: 0.05, turnRad: (2 * Math.PI) / 180 } as const;
