// A data file and the code that reads it cannot drift -- the shape
// `credits-data.test.ts` and `unit_icons.test.ts` established. This one pins
// the critical cue sets (polish pass F, docs/polish/audio-plan.md sections
// 2.3 and 4): each declared on the `ui` event `BattleAudio.playUi` plays
// unplaced, each shipping the one CC0 clip `tools/gen_audio.py` writes, at
// the gain the plan's mix table gives it. The two placeholder sets they
// replaced (`ui_alert`, `ui_objective`: no clip, one synth for every alert
// and one for every objective status) are gone.
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const REPO = fileURLToPath(new URL('../..', import.meta.url));

interface Variant {
  file: string;
  alt?: string;
  license: string;
  source: string;
}
const manifest = JSON.parse(readFileSync(`${REPO}data/audio.json`, 'utf8')) as {
  sets: Record<string, { event: string; gain?: number; variants: Variant[] }>;
};

/** Section 2.3's gains: confirm restrained, deny over combat, the alert tiers
 *  climbing, the outcome stingers the loudest cue in the game. */
const PLAN_GAINS: Record<string, number> = {
  ui_confirm: 0.2,
  ui_deny: 0.3,
  alert_minor: 0.25,
  alert_important: 0.45,
  alert_major: 0.6,
  objective_new: 0.4,
  objective_complete: 0.5,
  objective_failed: 0.5,
  mission_start: 0.55,
  victory: 0.7,
  defeat: 0.7,
};

describe('the critical cue sets (polish pass F)', () => {
  it.each(Object.entries(PLAN_GAINS))('%s is a ui set at gain %s with one CC0 clip from gen_audio.py', (name, gain) => {
    const set = manifest.sets[name];
    expect(set?.event).toBe('ui');
    expect(set?.gain).toBe(gain);
    expect(set?.variants).toEqual([
      {
        file: `${name}/${name}_01.ogg`,
        alt: `${name}/${name}_01.m4a`,
        license: 'CC0-1.0',
        source: 'generated by tools/gen_audio.py',
      },
    ]);
  });

  it('the alert tiers get louder as they climb, and the outcome is the loudest cue', () => {
    const g = (n: string): number => manifest.sets[n]?.gain ?? 0;
    expect(g('alert_minor')).toBeLessThan(g('alert_important'));
    expect(g('alert_important')).toBeLessThan(g('alert_major'));
    const loudest = Math.max(...Object.values(manifest.sets).filter((s) => s.event === 'ui').map((s) => s.gain ?? 1));
    expect(g('victory')).toBe(loudest);
    expect(g('defeat')).toBe(loudest);
  });

  it('the placeholder sets the cues replaced are gone', () => {
    expect(manifest.sets.ui_alert).toBeUndefined();
    expect(manifest.sets.ui_objective).toBeUndefined();
  });
});
