#!/usr/bin/env node
// Generates packages/sim/src/gen/tables.ts — the trig/exp/CDF lookup tables
// the Q16.16 sim uses instead of Math.* (invariant 2: Math.sin/cos/pow/exp
// are not bit-identical across JS engines).
//
//     pnpm gen:luts
//
// The generated file is COMMITTED and is the source of truth. Regenerating on
// a different engine may legitimately move a value by ±1 ulp; if that happens
// the determinism hash changes and test:determinism will say so. That is the
// point: the sim reads the committed integers and never computes them.

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const OUT_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'packages', 'sim', 'src', 'gen');
const OUT = join(OUT_DIR, 'tables.ts');
const ONE = 65536;

// Quarter-wave sine: SIN_Q[i] = sin((i/256) * pi/2) in Q16.16, i = 0..256.
// fx.sin reduces any angle to this quadrant with exact symmetry, so
// sin(-a) === -sin(a) holds bit-exactly.
const sinQ = [];
for (let i = 0; i <= 256; i++) sinQ.push(Math.round(Math.sin((i / 256) * (Math.PI / 2)) * ONE));
sinQ[0] = 0;
sinQ[256] = ONE;

// ATAN_T[i] = atan(i/256) in Q16.16 *turns* (full circle = 65536), i = 0..256.
// Covers ratios 0..1; octant reduction in fx.atan2 does the rest.
const atanT = [];
for (let i = 0; i <= 256; i++) atanT.push(Math.round((Math.atan(i / 256) / (2 * Math.PI)) * ONE));

// POW2NEG[i] = 2^(-i/256) in Q16.16, i = 0..256. fx.expNeg range-reduces
// e^-x = 2^(-x*log2(e)) into an integer shift plus one lookup here.
const pow2Neg = [];
for (let i = 0; i <= 256; i++) pow2Neg.push(Math.round(Math.pow(2, -i / 256) * ONE));

// NORM_CDF[i] = Phi(-4 + 8i/256) in Q16.16, i = 0..256 — the penetration
// curve (GDD 5.3). Mirrored around the center so Phi(x) + Phi(-x) == 1
// holds to within 1 ulp by construction.
function erf(z) {
  // Abramowitz & Stegun 7.1.26, |err| < 1.5e-7 — far below Q16.16 resolution.
  const s = z < 0 ? -1 : 1;
  const x = Math.abs(z);
  const t = 1 / (1 + 0.3275911 * x);
  const y =
    1 -
    ((((1.061405429 * t - 1.453152027) * t + 1.421413741) * t - 0.284496736) * t + 0.254829592) *
      t *
      Math.exp(-x * x);
  return s * y;
}
const normCdf = new Array(257);
for (let i = 0; i <= 128; i++) {
  normCdf[i] = Math.round(0.5 * (1 + erf((-4 + (8 * i) / 256) / Math.SQRT2)) * ONE);
}
normCdf[128] = ONE / 2;
for (let i = 0; i < 128; i++) normCdf[256 - i] = ONE - normCdf[i];

// Self-checks: every table must be monotone in the expected direction and
// integer-valued, or the sim's interpolation assumptions break.
function assertMonotone(name, arr, dir) {
  for (let i = 0; i < arr.length; i++) {
    if (!Number.isInteger(arr[i])) throw new Error(`${name}[${i}] not an integer`);
    if (i > 0 && Math.sign(arr[i] - arr[i - 1]) === -dir) {
      throw new Error(`${name} not monotone at ${i}`);
    }
  }
}
assertMonotone('SIN_Q', sinQ, 1);
assertMonotone('ATAN_T', atanT, 1);
assertMonotone('POW2NEG', pow2Neg, -1);
assertMonotone('NORM_CDF', normCdf, 1);

function emit(name, arr, doc) {
  const rows = [];
  for (let i = 0; i < arr.length; i += 16) rows.push('  ' + arr.slice(i, i + 16).join(', ') + ',');
  return `${doc}\nexport const ${name}: Int32Array = new Int32Array([\n${rows.join('\n')}\n]);\n`;
}

const body = [
  '// GENERATED by tools/gen_luts.mjs — DO NOT EDIT BY HAND. Regenerate: pnpm gen:luts',
  '// Committed as the deterministic source of truth: the sim reads these integers',
  '// and never calls Math.* (invariant 2). See tools/gen_luts.mjs for derivations.',
  '',
  emit('SIN_Q', sinQ, '/** Quarter-wave sine, Q16.16: SIN_Q[i] = sin((i/256) * pi/2). */'),
  emit('ATAN_T', atanT, '/** atan(i/256) in Q16.16 turns (65536 = full circle). */'),
  emit('POW2NEG', pow2Neg, '/** 2^(-i/256) in Q16.16. */'),
  emit('NORM_CDF', normCdf, '/** Phi(-4 + 8i/256) in Q16.16 — standard normal CDF. */'),
].join('\n');

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(OUT, body);
console.log(`wrote ${OUT}: SIN_Q[257] ATAN_T[257] POW2NEG[257] NORM_CDF[257]`);
