"""Guards validate_audio.py's UI-cue half (GH-238 plan 3, Task 7).

Run: python3 tools/test_validate_audio_ui.py
Exits non-zero on failure. Each case encodes a scratch Ogg Vorbis with ffmpeg's
own sine source into a temp directory, so nothing under assets/ is read or
written; the real clips are judged by `python3 tools/validate_audio.py`.
"""
import importlib.util
import os
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))


def load():
    spec = importlib.util.spec_from_file_location("validate_audio", os.path.join(HERE, "validate_audio.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def make(d, seconds, channels=1, peak_db=-6.0):
    # ffmpeg's sine source peaks at -18 dBFS, so the volume lifts it to peak_db.
    path = os.path.join(d, "cue.ogg")
    subprocess.run(
        ["ffmpeg", "-y", "-loglevel", "error", "-f", "lavfi", "-i", f"sine=frequency=880:duration={seconds}:sample_rate=44100",
         "-af", f"volume={peak_db + 18.0}dB", "-ac", str(channels), "-c:a", "libvorbis", "-q:a", "3", path],
        check=True,
    )
    return {"file": "cue.ogg", "source": "generated by tools/gen_audio.py"}


def main():
    mod = load()
    bad = []

    def check(label, entry_args, want):
        with tempfile.TemporaryDirectory() as d:
            entry = make(d, **entry_args)
            failures = []
            mod.check_ui_cue(entry, failures, audio_dir=d)
        ok = (not failures) if want is None else any(want in f for f in failures)
        print(f"{'ok  ' if ok else 'FAIL'} {label}" + ("" if ok else f" -- got {failures}"))
        if not ok:
            bad.append(label)

    check("a 200 ms mono -6 dB cue passes", dict(seconds=0.2), None)
    check("a 300 ms cue fails on length", dict(seconds=0.3), "over the 250 ms ceiling")
    check("a stereo cue fails on channels", dict(seconds=0.2, channels=2), "must be mono")
    check("a 0 dBFS cue fails on peak", dict(seconds=0.2, peak_db=0.0), "dBFS ceiling")

    # A hand-dropped clip with another source is not this check's business.
    with tempfile.TemporaryDirectory() as d:
        entry = make(d, seconds=0.3)
        entry["source"] = "https://example.org/clip"
        failures = []
        mod.check_ui_cue(entry, failures, audio_dir=d)
        ok = not failures
        print(f"{'ok  ' if ok else 'FAIL'} a clip not generated by gen_audio.py is skipped")
        if not ok:
            bad.append("skipped")

    if bad:
        print(f"\n{len(bad)} case(s) failed")
        return 1
    print("\nall UI-cue cases passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
