"""Guards validate_audio.py's polish pass F checks: the cue map's shape, the
music levels (A10, F4) and the commercial-build gate (A3).

Run: python3 tools/test_validate_audio_mix.py
Exits non-zero on failure. Dependency-free, like test_validate_audio_voices.py:
every case builds a manifest fragment and, where a file must exist, a scratch
directory, and the true-peak reader is replaced by a fixed number, so neither
ffmpeg nor anything under assets/ is touched.
"""
import importlib.util
import os
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))


def load():
    spec = importlib.util.spec_from_file_location("validate_audio", os.path.join(HERE, "validate_audio.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def main():
    mod = load()
    bad = []

    def check(label, failures, want):
        ok = (not failures) if want is None else any(want in f for f in failures)
        print(f"{'ok  ' if ok else 'FAIL'} {label}" + ("" if ok else f" -- got {failures}"))
        if not ok:
            bad.append(label)

    sets = {"victory": {"event": "ui"}, "small_arms": {"event": "fire"}}

    def cues(table):
        failures = []
        mod.check_cues({"sets": sets, "cues": table}, failures)
        return failures

    check("a cue on a declared ui set passes", cues({"$comment": "x", "outcome.victory": "victory"}), None)
    check("a cue on an undeclared set fails", cues({"outcome.victory": "victroy"}), "is not declared in sets")
    check("a cue on a battle set fails", cues({"alert.minor": "small_arms"}), "not 'ui'")
    check("a reasoned silence passes", cues({"ui.hover": {"silent": "hover is never a sound"}}), None)
    check("a silence with no reason fails", cues({"ui.hover": {"silent": " "}}), "must be a set name")
    check("a cue that is neither fails", cues({"ui.hover": 3}), "must be a set name")

    def levels(music, tp):
        with tempfile.TemporaryDirectory() as d:
            os.makedirs(os.path.join(d, "music"))
            with open(os.path.join(d, "music", "t.mp3"), "wb") as fh:
                fh.write(b"ID3")
            failures, notes = [], []
            mod.check_music_levels(music, failures, notes, audio_dir=d, measure=lambda _p: tp)
            return failures, notes

    track = {"file": "music/t.mp3"}
    check("the theme's +0.2 dBTP with no trim fails", levels({"tracks": [track]}, 0.2)[0], "over -1.0 dBTP")
    check("-1.2 dB of trim clears it", levels({"tracks": [dict(track, trim_db=-1.2)]}, 0.2)[0], None)
    check("-1.0 dB of trim is 0.2 short", levels({"tracks": [dict(track, trim_db=-1.0)]}, 0.2)[0], "trim it by at least 0.2 dB more")
    check("a positive trim fails", levels({"tracks": [dict(track, trim_db=1.0)]}, -6.0)[0], "trim_db 1.0 outside")
    check("a non-numeric trim fails cleanly", levels({"tracks": [dict(track, trim_db="loud")]}, -6.0)[0], "outside")
    check("battle_gain above 1 fails", levels({"battle_gain": 1.5, "tracks": []}, 0.0)[0], "battle_gain 1.5 outside")
    check("battle_gain 0.26 passes", levels({"battle_gain": 0.26, "tracks": []}, 0.0)[0], None)
    f, n = levels({"tracks": [track]}, None)
    check("no ffmpeg is a named skip, not a pass or a failure", f, None)
    ok = any("NOT measured" in x for x in n)
    print(f"{'ok  ' if ok else 'FAIL'} the skip is named in the notes")
    if not ok:
        bad.append("skip named")

    def commercial(source):
        failures = []
        man = {"voices": {"lines": {"he.common.ack": {"variants": [{"file": "voice/he/common/ack_01a.ogg", "source": source}]}}}}
        mod.check_commercial(man, failures)
        return failures

    shipped = ("ElevenLabs (generated by the project lead, plan and date not recorded); "
               "commercial licence NOT yet confirmed (D5 deferred by the lead 29 Sep 2026)")
    check("an unconfirmed ElevenLabs take fails a commercial build", commercial(shipped), "cannot ship in a commercial build")
    check("a recorded take with a release passes", commercial("session record 2026-10-10, release form RL-V-001"), None)
    check("a set variant is held to it too", (lambda f: (mod.check_commercial(
        {"sets": {"x": {"variants": [{"file": "x/x_01.ogg", "source": "licence not confirmed"}]}}}, f), f)[1])([]),
        "cannot ship")

    # AU-10: the commercial manifest. What the release step ships is the
    # shipped manifest with every unconfirmed variant taken out; it must pass
    # the commercial gate, and the files it leaves out are exactly the
    # ElevenLabs takes (five takes on four keys, two encodings each).
    import json
    with open(os.path.join(HERE, "..", "data", "audio.json")) as fh:
        shipped_man = json.load(fh)
    stripped, excluded = mod.commercial_manifest(shipped_man)
    failures = []
    mod.check_commercial(stripped, failures)
    check("the commercial manifest passes the commercial gate", failures, None)
    failures = []
    mod.check_commercial(shipped_man, failures)
    check("...while the shipped manifest still fails it (the gate is not vacuous)", failures, "cannot ship in a commercial build")
    want = sorted(f"voice/he/{p}.{ext}" for p in ("infantry/move_01a", "infantry/attack_01a", "infantry/death_01a",
                                                 "infantry/death_02a", "common/ack_01a") for ext in ("ogg", "m4a"))
    ok = sorted(excluded) == want
    print(f"{'ok  ' if ok else 'FAIL'} it leaves out exactly the ten ElevenLabs files -> {sorted(excluded)}")
    if not ok:
        bad.append("excluded files")
    lines = stripped["voices"]["lines"]
    ok = all(lines[k]["variants"] == [] for k in ("he.infantry.move", "he.infantry.death", "he.common.ack"))
    ok = ok and set(lines) == set(shipped_man["voices"]["lines"])
    print(f"{'ok  ' if ok else 'FAIL'} every key stays declared, its stripped takes an empty list (plays nothing)")
    if not ok:
        bad.append("stripped keys")
    # The lead's own recordings (9 Oct 2026) are his voice, not generated:
    # they stay in a commercial build, the attack key keeping his take alone.
    kept = {k: [v["file"] for v in line["variants"]] for k, line in lines.items() if line["variants"]}
    ok = kept == {
        "he.infantry.attack": ["voice/he/infantry/attack_02a.ogg"],
        **{f"he.common.announce_{e}": [f"voice/he/common/announce_{e}_01a.ogg"]
           for e in ("mission_start", "objective_active", "objective_complete", "objective_failed", "reinforcements")},
    }
    print(f"{'ok  ' if ok else 'FAIL'} the lead's recorded takes stay in a commercial build -> {kept}")
    if not ok:
        bad.append("keys kept")
    ok = shipped_man["voices"]["lines"]["he.common.ack"]["variants"] != []
    print(f"{'ok  ' if ok else 'FAIL'} the shipped manifest is not mutated")
    if not ok:
        bad.append("not mutated")
    music_kept = stripped.get("music") == shipped_man.get("music") and stripped.get("sets") == shipped_man.get("sets")
    print(f"{'ok  ' if music_kept else 'FAIL'} a confirmed section (sets, music) is left exactly as it was")
    if not music_kept:
        bad.append("confirmed kept")

    code = mod.main(["--nope"])
    ok = code == 2
    print(f"{'ok  ' if ok else 'FAIL'} an unknown argument exits 2 -> {code}")
    if not ok:
        bad.append("unknown argument")

    if bad:
        print(f"\nmix gate: {len(bad)} case(s) failed")
        return 1
    print("\nmix gate: all cases pass")
    return 0


if __name__ == "__main__":
    sys.exit(main())
