"""Guards validate_audio.py's ambience check (polish pass F, A11).

Run: python3 tools/test_validate_audio_ambience.py
Exits non-zero on failure. Dependency-free, like test_validate_audio_mix.py:
every case builds a manifest fragment over a scratch directory, and the
decoder (`measure`) is replaced by fixed readings, so neither ffmpeg nor
anything under assets/ is touched. The seam arithmetic is exercised on
synthetic PCM directly.

What the real files read, and the one-line mutations of tools/gen_audio.py
that turn the real gate red, are in the commit that added this file.
"""
import importlib.util
import math
import os
import random
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))


def load():
    spec = importlib.util.spec_from_file_location("validate_audio", os.path.join(HERE, "validate_audio.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


GOOD = {"channels": 1, "seconds": 40.008, "integrated": -26.0, "true_peak": -9.0, "seam_level_db": 0.3, "seam_gap_db": 3.0}


def main():
    mod = load()
    bad = []

    def check(label, failures, want):
        ok = (not failures) if want is None else any(want in f for f in failures)
        print(f"{'ok  ' if ok else 'FAIL'} {label}" + ("" if ok else f" -- got {failures}"))
        if not ok:
            bad.append(label)

    def bed(**over):
        b = {
            "file": "ambience/amb_open.ogg", "alt": "ambience/amb_open.m4a", "gain": 0.44, "loop_s": 40.008,
            "channels": 1, "license": "CC0-1.0", "source": "generated by tools/gen_audio.py",
        }
        b.update(over)
        return b

    def run(beds, reading=None, master=0.9):
        """(failures, notes, declared). `reading` is what every file decodes to;
        None stands for no ffmpeg on PATH."""
        with tempfile.TemporaryDirectory() as d:
            os.makedirs(os.path.join(d, "ambience"))
            for name in ("amb_open.ogg", "amb_open.m4a"):
                with open(os.path.join(d, "ambience", name), "wb") as fh:
                    fh.write(b"OggS")
            failures, notes = [], []
            man = {"master_gain": master, "ambience": {"beds": beds}}
            declared = mod.check_ambience(man, failures, notes, audio_dir=d, measure=lambda _p: reading)
            return failures, notes, declared

    f, n, declared = run({"open": bed()}, GOOD)
    check("a bed that decodes to its declaration passes", f, None)
    ok = declared == {"ambience/amb_open.ogg", "ambience/amb_open.m4a"}
    print(f"{'ok  ' if ok else 'FAIL'} both encodings are declared for the undeclared-file sweep")
    if not ok:
        bad.append("declared")
    ok = any("heard -34.0 LUFS" in x for x in n)
    print(f"{'ok  ' if ok else 'FAIL'} the heard level is file + gain + master ({[x for x in n][:1]})")
    if not ok:
        bad.append("heard arithmetic")

    check("no beds at all fails", run({}, GOOD)[0], "no beds declared")
    check("a bed with no file fails", run({"open": {"gain": 0.4}}, GOOD)[0], "no file")
    check("a gain over 1 fails", run({"open": bed(gain=1.2)}, GOOD)[0], "gain 1.2 outside")
    check("a zero gain fails", run({"open": bed(gain=0)}, GOOD)[0], "gain 0 outside")
    check("a 5 s loop fails", run({"open": bed(loop_s=5.0)}, GOOD)[0], "loop_s 5.0 outside")
    check("three channels fail", run({"open": bed(channels=3)}, GOOD)[0], "is not 1 (mono) or 2")
    check("a non-CC licence fails", run({"open": bed(license="royalty-free")}, GOOD)[0], "not redistribution-safe")
    check("a missing encoding fails", run({"open": bed(alt="ambience/amb_gone.m4a")}, GOOD)[0], "missing from assets/audio/")

    check("a stereo file declared mono fails", run({"open": bed()}, dict(GOOD, channels=2))[0], "decodes to 2 channel(s)")
    check("AAC priming left in (23 ms long) fails", run({"open": bed()}, dict(GOOD, seconds=40.0312))[0], "priming or padding")
    check("a loop 0.5 ms long still passes", run({"open": bed()}, dict(GOOD, seconds=40.0085))[0], None)
    check("a peak over -6 dBTP fails", run({"open": bed()}, dict(GOOD, true_peak=-5.5))[0], "over the bed ceiling")
    check("a bed 3 LU too loud fails", run({"open": bed()}, dict(GOOD, integrated=-23.0))[0], "outside -34.0 +- 2.0")
    check("a bed 3 LU too quiet fails", run({"open": bed()}, dict(GOOD, integrated=-29.1))[0], "outside -34.0 +- 2.0")
    check("a 3 dB step at the seam fails", run({"open": bed()}, dict(GOOD, seam_level_db=3.0))[0], "seam steps 3.0 dB")
    check("a gap at the seam fails", run({"open": bed()}, dict(GOOD, seam_gap_db=-20.0))[0], "a gap at the loop's seam")

    f, n, _ = run({"open": bed()}, None)
    check("no ffmpeg is a named skip, not a pass or a failure", f, None)
    ok = any("NOT measured" in x for x in n)
    print(f"{'ok  ' if ok else 'FAIL'} the skip is named in the notes")
    if not ok:
        bad.append("skip named")

    # The seam arithmetic itself, on a second of noise looped.
    rate = 8000
    rng = random.Random(7)
    pcm = [rng.gauss(0, 0.05) for _ in range(rate * 4)]
    level, gap = mod.seam_metrics(pcm, rate)
    check("steady noise: no step, no gap", [] if level < 1.0 and gap > -6.0 else [f"{level} {gap}"], None)
    stepped = pcm[: -rate // 4] + [v * 0.3 for v in pcm[-rate // 4:]]
    level, _ = mod.seam_metrics(stepped, rate)
    check("the last 250 ms 10 dB down reads as a step", [f"step {level:.1f}"] if level > 8 else [], "step")
    primed = [0.0] * 1024 + pcm[:-1024]
    _, gap = mod.seam_metrics(primed, rate)
    check("1024 samples of priming silence read as a gap", [f"gap {gap}"] if gap < -60 or math.isinf(gap) else [], "gap")

    if bad:
        print(f"\n{len(bad)} ambience case(s) failed", file=sys.stderr)
        return 1
    print("validate_audio ambience: OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
